[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://newsapi.org/v2/top-headlines/sources?country="
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"